[versions]
agp = "8.3.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
constraintlayout = "2.1.4"
lifecycleLivedataKtx = "2.7.0"
lifecycleViewmodelKtx = "2.7.0"
navigationFragment = "2.7.7"
navigationUi = "2.7.7"
activity = "1.8.2"
volley = "1.2.1"
okhttp = "4.9.0"
#libvlc = "3.3.0"
appauth = "0.11.1"
lombok = "1.18.32"
gson = "2.10.1"
worker = "2.7.0"
annotation = "1.0.2"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
#libvlc = { group = "org.videolan.android", name = "libvlc-all", version.ref = "libvlc" }
appauth = { group = "net.openid", name = "appauth", version.ref = "appauth" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
worker = { group = "androidx.work", name = "work-runtime", version.ref = "worker" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
